/*
 * DCWATCH ↔ OPENSTREETMAP — matching a power figure onto a footprint.
 *
 * The bundled OSM datacenter pack draws 372 French sites and can say what
 * almost none of them CONSUME: `data_center:power` is set on five features in
 * the whole country (1.3 %), all five at Marseille. Every other power-shaped
 * key in the pack — `capacity:it_load`, `it_load`, `capacity` — matches one
 * feature each. OSM simply does not carry this number.
 *
 * DCWatch does. It is a collaborative research database (Hubblo, after the
 * ADEME/Arcep work published January 2026) covering 520 sites in France,
 * Switzerland, Belgium, Luxembourg and Monaco, and it is ODbL — the same
 * licence as the OSM pack it is being joined to, so the share-alike obligation
 * this repo already carries for datacenters and dams is unchanged.
 *
 * Over the 418 geolocated French rows:
 *
 *     power_total_mw         400  93.7 %   a NUMBER in MW, not a band
 *     total_floor_area_sqm   375  87.8 %
 *     IT_floor_area_sqm      371  86.9 %
 *     operation_start_year   274  64.2 %
 *     operator               427  100 %
 *
 * PUE, WUE, CUE, ERF, REF, tier, cooling technology and heat recovery are
 * columns in the schema and are EMPTY in every one of the 524 rows. The schema
 * promises an environmental profile the dump does not deliver, and nothing
 * downstream may present those as available.
 *
 * ── WHY THE MATCH NEEDS MORE THAN A DISTANCE ────────────────────────────────
 *
 * DCWatch coordinates are rounded to three decimals — about 110 m of slack at
 * this latitude — and a datacenter campus routinely puts seven buildings
 * inside 250 m. Nearest-neighbour alone therefore does not pick a building, it
 * picks a campus, and then hands it whichever MW figure happens to be closest.
 * Measured on this pack, plain nearest-neighbour produced:
 *
 *     OVHCloud RBX-2  → OVHcloud Roubaix - RBX6      (six buildings, scrambled)
 *     CIVICOS ROUBAIX → OVHcloud Roubaix - RBX4      (different operator)
 *     COGENT STRASBOURG → Quiri                      (a machine-tool firm)
 *
 * The last two matched because the CITY NAME survived into the identity
 * comparison and "roubaix" is not evidence of anything. So the identity test
 * strips the row's own `city_name` from both sides before comparing: what is
 * left is the operator and the site's own designation.
 *
 * The first is worse, because operator and city both agree and only the
 * building number disagrees. {@link refNumbers} extracts trailing numeric refs
 * — RBX-2, SBG3, PAR9, MRS1, DC01 — and a pair whose two sides both carry one
 * must AGREE on it. RBX-2 against RBX6 is not a near miss to be tolerated at
 * 27 m; it is a 5 MW figure printed on the wrong hall.
 *
 * What survives both guards is reported as a match. What does not is left
 * unmatched, and an unmatched DCWatch site in operation is not a failure — it
 * is a datacenter OSM has never mapped, which is most of them.
 *
 * Source:  DCWatch, https://gitlab.com/hubblo/datacenter-watch — ODbL.
 * See also: src/data/local_data/datacenters/dcwatch/SOURCE.md
 */

/** Match radius, metres. */
export const DCWATCH_MATCH_RADIUS_M = 250;

/**
 * Words that describe what a thing IS rather than which one it is.
 *
 * Every one of these appears on both sides of the join often enough that
 * letting it corroborate an identity would corroborate everything: 'datacenter'
 * is in the name of a third of the OSM pack.
 */
const GENERIC = new Set([
  'data', 'datacenter', 'datacenters', 'center', 'centre', 'centers', 'centres',
  'de', 'du', 'la', 'le', 'les', 'des', 'et', 'site', 'technique', 'salle',
  'dc', 'campus', 'group', 'groupe', 'sa', 'sas', 'sarl', 'inc', 'company',
  'ltd', 'llc', 'services', 'service', 'international', 'corporation', 'europe',
  'france', 'french', 'projet', 'project', 'batiment', 'building', 'nord', 'sud',
  'est', 'ouest', 'autogenerated', 'ex', 'confirmer', 'telecom', 'telecoms',
]);

/**
 * Operator names the two vocabularies spell differently for the same company.
 *
 * Each entry is a token seen in one source mapped to the token the other uses.
 * Interxion was bought by Digital Realty and both names are still in the wild;
 * SFR's datacenter estate was sold to UltraEdge in 2024 and OSM still says
 * SFR (and, on older features, Completel); Online is Scaleway's former name.
 */
const OPERATOR_ALIASES = new Map(Object.entries({
  interxion: 'digitalrealty',
  digital: 'digitalrealty',
  realty: 'digitalrealty',
  reality: 'digitalrealty',
  ultraedge: 'ultraedge',
  sfr: 'ultraedge',
  completel: 'ultraedge',
  online: 'scaleway',
  iliad: 'scaleway',
  ovhcloud: 'ovh',
  kddi: 'telehouse',
  cogentco: 'cogent',
}));

/** Strip accents, case and punctuation. */
export function normalise(value) {
  return String(value ?? '')
    .normalize('NFD')
    .replace(/[̀-ͯ]/g, '')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, ' ')
    .trim();
}

/**
 * Identity tokens of a free-text designation, minus the noise.
 *
 * @param {string} value Raw text — an operator, a name, a ref, or all three.
 * @param {Iterable<string>} [drop] Extra tokens to remove (a city name).
 * @returns {Set<string>}
 */
export function identityTokens(value, drop = []) {
  const dropped = new Set();
  for (const word of drop) for (const t of normalise(word).split(' ')) if (t) dropped.add(t);
  const out = new Set();
  for (const raw of normalise(value).split(' ')) {
    // Single characters carry no identity, and a bare number is a building
    // index handled by refNumbers() rather than a name.
    if (raw.length < 2 || GENERIC.has(raw) || dropped.has(raw)) continue;
    if (/^\d+$/.test(raw)) continue;
    out.add(OPERATOR_ALIASES.get(raw) ?? raw);
  }
  return out;
}

/**
 * Building indices embedded in a designation, keyed by their alphabetic stem.
 *
 * 'OVHCloud RBX-2' and 'OVHcloud Roubaix - RBX6' both reduce to stem `rbx`,
 * with 2 and 6 — which is exactly the disagreement a distance test cannot see.
 *
 * The stem is allowed up to twelve letters so that 'Telehouse 2' yields
 * `telehouse`→2, and generic stems are dropped so that 'DC01' and 'DATA4' do
 * not pretend to index anything: `dc` describes what the thing is, and the 4
 * in DATA4 is a company, not a hall.
 *
 * @param {string} value
 * @returns {Map<string, Set<number>>} stem → the indices seen for it.
 */
export function refNumbers(value) {
  const out = new Map();
  for (const m of normalise(value).matchAll(/\b([a-z]{2,12})\s?0*(\d{1,3})\b/g)) {
    const stem = OPERATOR_ALIASES.get(m[1]) ?? m[1];
    if (GENERIC.has(m[1])) continue;
    if (!out.has(stem)) out.set(stem, new Set());
    out.get(stem).add(Number(m[2]));
  }
  return out;
}

/**
 * Do two designations disagree about a building index they both name?
 *
 * Only a SHARED stem can disagree: a DCWatch row saying `RBX-2` against an OSM
 * feature that names no ref at all is not a contradiction, it is silence, and
 * silence is resolved by distance. Two rows that both say `rbx` and mean
 * different halls are a contradiction, and it is fatal.
 *
 * @returns {boolean} true when the pair must be refused.
 */
export function refsContradict(a, b) {
  const left = refNumbers(a);
  const right = refNumbers(b);
  for (const [stem, leftNumbers] of left) {
    const rightNumbers = right.get(stem);
    if (!rightNumbers) continue;
    let shared = false;
    for (const n of leftNumbers) if (rightNumbers.has(n)) shared = true;
    if (!shared) return true;
  }
  return false;
}

/** Metres between two `[lon, lat]` pairs, flat-Earth at the first one. */
export function metresBetween(a, b) {
  const lat0 = (a[1] * Math.PI) / 180;
  return Math.hypot((b[0] - a[0]) * 111320 * Math.cos(lat0), (b[1] - a[1]) * 111320);
}

/**
 * Is `point` inside any ring of `geometry`? Even-odd, outer rings only.
 *
 * Inner rings are ignored on purpose: a courtyard inside a datacenter block is
 * still that datacenter's parcel, and a DCWatch point landing in one should
 * not be pushed out to a neighbour.
 */
export function pointInGeometry(point, geometry) {
  const rings = geometry?.type === 'Polygon'
    ? [geometry.coordinates?.[0]]
    : (geometry?.type === 'MultiPolygon' ? geometry.coordinates?.map((p) => p?.[0]) : null);
  if (!Array.isArray(rings)) return false;
  for (const ring of rings) {
    if (!Array.isArray(ring) || ring.length < 3) continue;
    let inside = false;
    for (let i = 0, j = ring.length - 1; i < ring.length; j = i, i += 1) {
      const xi = ring[i][0]; const yi = ring[i][1];
      const xj = ring[j][0]; const yj = ring[j][1];
      if ((yi > point[1]) !== (yj > point[1])
        && point[0] < ((xj - xi) * (point[1] - yi)) / (yj - yi) + xi) inside = !inside;
    }
    if (inside) return true;
  }
  return false;
}

/**
 * Pair every DCWatch row that can be pinned to an OSM feature, one to one.
 *
 * Candidates are collected first and assigned afterwards, closest pair first,
 * so that a campus of seven buildings distributes seven rows instead of
 * handing all seven to whichever building the iteration reached first.
 *
 * @param {Array<{point:[number,number], identity:string, city?:string, ref?:string}>} rows
 *   DCWatch side. `identity` is operator + name; `ref` defaults to `identity`.
 * @param {Array<{centre:[number,number], geometry?:object, identity:string, ref?:string}>} features
 *   OSM side.
 * @param {{radiusM?:number}} [options]
 * @returns {{pairs: Array<{rowIndex:number, featureIndex:number, metres:number}>,
 *            unmatchedRows: number[], refusedByRef: number}}
 */
export function matchDcwatchToOsm(rows, features, { radiusM = DCWATCH_MATCH_RADIUS_M } = {}) {
  const featureTokens = features.map((f) => f.identity);
  const candidates = [];
  let refusedByRef = 0;

  for (let r = 0; r < rows.length; r += 1) {
    const row = rows[r];
    const rowRef = row.ref ?? row.identity;
    for (let f = 0; f < features.length; f += 1) {
      const feature = features[f];
      const metres = pointInGeometry(row.point, feature.geometry)
        ? 0
        : metresBetween(row.point, feature.centre);
      if (metres > radiusM) continue;

      // The city is stripped from BOTH sides: it is the one word guaranteed to
      // appear on any two datacenters that are near each other, which is
      // precisely the population this loop is trying to tell apart.
      const drop = row.city ? [row.city] : [];
      const left = identityTokens(row.identity, drop);
      const right = identityTokens(featureTokens[f], drop);
      let agrees = false;
      for (const token of left) if (right.has(token)) agrees = true;
      if (!agrees) continue;

      if (refsContradict(rowRef, feature.ref ?? feature.identity)) { refusedByRef += 1; continue; }
      candidates.push({ rowIndex: r, featureIndex: f, metres });
    }
  }

  candidates.sort((a, b) => a.metres - b.metres);
  const takenRow = new Set();
  const takenFeature = new Set();
  const pairs = [];
  for (const candidate of candidates) {
    if (takenRow.has(candidate.rowIndex) || takenFeature.has(candidate.featureIndex)) continue;
    takenRow.add(candidate.rowIndex);
    takenFeature.add(candidate.featureIndex);
    pairs.push(candidate);
  }
  const unmatchedRows = [];
  for (let r = 0; r < rows.length; r += 1) if (!takenRow.has(r)) unmatchedRows.push(r);
  return { pairs, unmatchedRows, refusedByRef };
}

/**
 * Minimal RFC 4180 reader — quoted fields, doubled quotes, CRLF.
 *
 * The DCWatch export quotes addresses that contain commas and nothing else, so
 * a dependency would buy nothing here.
 *
 * @param {string} text
 * @returns {Array<Record<string,string>>}
 */
export function parseCsv(text) {
  const rows = [];
  let row = [];
  let cell = '';
  let quoted = false;
  for (let i = 0; i < text.length; i += 1) {
    const c = text[i];
    if (quoted) {
      if (c !== '"') { cell += c; continue; }
      if (text[i + 1] === '"') { cell += '"'; i += 1; continue; }
      quoted = false;
      continue;
    }
    if (c === '"') { quoted = true; continue; }
    if (c === ',') { row.push(cell); cell = ''; continue; }
    if (c === '\n') { row.push(cell); rows.push(row); row = []; cell = ''; continue; }
    if (c !== '\r') cell += c;
  }
  if (cell !== '' || row.length) { row.push(cell); rows.push(row); }
  const header = rows.shift();
  if (!header) return [];
  return rows
    .filter((r) => r.length === header.length)
    .map((r) => Object.fromEntries(header.map((h, i) => [h.trim(), r[i]])));
}
